### ISSUE TITLE
[Feature request] Supporting multiple values for an argument

### ISSUE THREAD

**Issue by rooa** [huzecong/argtyped#1]
It would be great to support multiple values for a single argument:

* commandline argument:`--elements 1 2 3`
* parsed value: `[1, 2, 3]`

with code like below:
```python

class Args(argtyped.Arguments):
    elements: List[int]
```

**Comment by guhur** [comment]
I support this feature request. I really like this lib, thanks, but I often need to go back to argparse because of this missing feature.

**Comment by huzecong** [comment]
Thank you for your interests in `argtyped`! I plan to work on this during the upcoming vacation. Stay tuned!

**Comment by huzecong** [comment]
This feature is now implemented in the latest version (v0.3.0). Closing the issue.
