### ISSUE TITLE
Implement the __repr__ method

### ISSUE THREAD

**Issue by guhur** [huzecong/argtyped#2]
It's quite practical to `print(args)`. Right now the class `Arguments` does not support it.
Do you plan on using `to_string` for that?

By the way, I am not sure `to_string` is a good function name. `to_table` seems more appropriate.

**Comment by huzecong** [comment]
This is a good point. I think the reason I did not add `__repr__` or `__str__` was to encourage the use of `to_string()`, which allows explicitly setting max width. But I guess it'd be beneficial to let `__repr__` print the table with a reasonable max width.

Regarding the method name, I actually think `to_string` is more informative than `to_table`; I would imagine `to_table` returning some kind of table data structure, such as a pandas DataFrame or sorts.

**Comment by huzecong** [comment]
`__repr__` is implemented as of v0.3.0. It calls `.to_string()` with `max_width` set to the terminal's width (or 80 if not a terminal). Closing the issue.

**Comment by guhur** [comment]
Thanks!
