### ISSUE TITLE
Support for underscore

### ISSUE THREAD

**Issue by guhur** [huzecong/argtyped#6]
Underscores are using by many tools to inject parameters in program. 

For example, in [`pytorch.distributed.run`](https://pytorch.org/docs/stable/distributed.html#launch-utility), the argument `local_rank` is added.

That would be nice to support this type of arguments in Argtyped. Workarounds are very clumsy.

**Comment by huzecong** [comment]
I initially chose kebab-case arguments over snake_case for consistency with most Linux CLI tools, but I guess compatibility with external flags is also a valid case.

I propose an API where you can set the argument style for all arguments in a class, something like this:
```python
class MyArgs(Arguments, snake_case=True):  # defaults to False
    snake_case_arg: str

_ = MyArgs("--snake_case_arg snake".split())  # this works
# _ = MyArgs("--snake-case-arg snake".split())  # this won't
```
Then, to mix together arguments with different styles (maybe you want most of your own arguments to be kebab-case, but still support snake_case for external flags), you can use inheritance:
```python
class MyOtherArgs(Arguments):
    kebab_case_arg: str

class AllArgs(MyArgs, MyOtherArgs):
    pass

_ = AllArgs("--snake_case_arg snake --kebab-case-arg kebab".split())
```

Alternatively, we can try to support both styles for all arguments. I'll have to experiment a bit with `argparse` to see if we can easily support that.

Let me know your thoughts on this.

**Comment by guhur** [comment]
Hi @huzecong ! Thanks so much for your answer! I prefer rather the option 1. It sounds neat to me.

**Comment by huzecong** [comment]
Cool! I might not have time to work on this before the weekend, but I'll get it done within the week.

**Comment by huzecong** [comment]
I've uploaded v0.3.1 of `argtyped` which adds support for `snake_case` (underscore style) arguments. I've also updated the README. Have a try!

**Comment by guhur** [comment]
Really cool thanks!
